---
- hosts: all
  sudo: yes
  remote_user: pablo

  tasks:
    - name: Actualización de repositorios
      apt:
          update_cache: yes

    - name: Build-essential
      command: apt-get install -y build-essential

    - name: Install git 
      command: apt-get install -y git 

    - name: Instalar pip3
      apt: name=python3-pip state=present
    
    - name: Instalar flask
      command: sudo pip3 install Flask
  
    - name: Instalación de paquetes requeridos.
      apt: name=git state=present
      apt: name=python3 state=present
      apt: name=libpq-dev state=present
      apt: name=python-dev state=present
      apt: name=python-setuptools state=present

    - name: Clonar
      shell: rm -rf proyecto && git clone https://github.com/pmolinag/proyecto

    - name: Instalar supervisor
      apt: name=supervisor state=present

    - name: Update
      command: apt-get update

    - name: Instalar requirements
      command: sudo pip3 install -r proyecto/requirements.txt


